sudo: required
group: edge
env:
  - DEBREW_HIDDEN_REPO=true DEBREW_HIDDEN_REPO_PATH=ftp://it-the-drote.tk/hidden/

services:
  - docker

script:
  - wget -O- http://dev.crapcannon.tk/scripts/travis-debian.sh | bash -
