#!/bin/sh

environment=`cat /etc/apps/environment.type`

useradd apps
chown -R www-data:www-data /opt/it-the-drote/public/
deb-systemd-invoke enable /lib/systemd/system/it-the-drote.service
ln -s "/etc/nginx/sites-available/it-the-drote."$environment".nginx" /etc/nginx/sites-enabled/it-the-drote.nginx
deb-systemd-invoke reload nginx.service
deb-systemd-invoke restart rsyslog.service
deb-systemd-invoke start it-the-drote.service
